# Generated by Django 3.1.1 on 2020-09-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vendor', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ManyToManyField(blank=True, to='vendor.TaxClassifier'),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='vendor.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='reciepts',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sites.site'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
