# Generated by Django 3.0.7 on 2020-06-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('core', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ManyToManyField(blank=True, to='vendor.ProductClassifier'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
