# Generated by Django 3.1 on 2020-08-19 00:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200814_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='User Defineable SKU field', max_length=40, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique_with=('site__id',)),
            preserve_default=False,
        ),
    ]
