# Generated by Django 2.2.4 on 2019-08-10 22:35

from django.db import migrations, models
import vendor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=vendor.models.generate_sku, max_length=8, verbose_name='SKU'),
        ),
    ]
