# Generated by Django 3.1 on 2020-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200819_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta'),
        ),
    ]
