# Generated by Django 3.1.3 on 2020-11-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0003_auto_20200917_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sites.site', verbose_name='Site'),
        ),
    ]
