# Generated by Django 3.1 on 2020-08-21 22:38

from django.db import migrations, models
import vendor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200820_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.CharField(blank=True, help_text='Eg: 840,10.99\n(iso4217 Country Code), (MSRP Price)', max_length=150, null=True, validators=[vendor.models.validate_msrp_format], verbose_name='Meta'),
        ),
    ]
