# Generated by Django 3.1.3 on 2020-11-18 22:37

from django.db import migrations, models
import vendor.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201112_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.JSONField(blank=True, default=vendor.models.base.product_meta_default, help_text="Eg: { 'msrp':{'usd':10.99} }\n(iso4217 Country Code):(MSRP Price)", null=True, validators=[vendor.models.base.validate_msrp], verbose_name='Meta'),
        ),
    ]
