# Generated by Django 2.2.7 on 2019-11-14 20:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191015_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
