# Generated by Django 3.1 on 2020-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200901_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Description'),
        ),
    ]
