# Generated by Django 5.2.9 on 2025-12-18 16:38

import autoslug.models
import django.db.models.deletion
import vendor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModeltranslationOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithAcceptableEmptyDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date",))),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithAutoUpdateEnabled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithBlank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithBooleanInUniqueWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bool", models.BooleanField()),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="name", unique_with=("bool",)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCallable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from=autoslug.models.get_callable_slug
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCallableAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="get_name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCustomPrimaryKey",
            fields=[
                (
                    "custom_primary_key",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCustomSeparator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", vendor.fields.AutoSlugField(sep="_", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCustomSlugifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        slugify=autoslug.models.custom_slugify, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithLongName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(editable=False, populate_from="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithLongNameUnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithNullable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        blank=True, editable=False, null=True, populate_from="name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithReferenceToItself",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", vendor.fields.AutoSlugField(unique_with=("slug",))),
            ],
        ),
        migrations.CreateModel(
            name="SharedSlugSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date",))),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date__day",))),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date__month",))),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date__year",))),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithWrongFieldOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", vendor.fields.AutoSlugField(unique_with=("date",))),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithWrongLookupInUniqueWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", vendor.fields.AutoSlugField(unique_with=("name__foo",))),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithWrongReferencedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", vendor.fields.AutoSlugField(unique_with=("wrong_field",))),
            ],
        ),
        migrations.CreateModel(
            name="NonDeletableModelWithUniqueSlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False,
                        manager_name="all_objects",
                        populate_from="name",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", vendor.fields.AutoSlugField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithSlugSpaceShared",
            fields=[
                (
                    "sharedslugspace_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="autoslug.sharedslugspace",
                    ),
                ),
            ],
            bases=("autoslug.sharedslugspace",),
        ),
        migrations.CreateModel(
            name="ModelWithSlugSpaceSharedIntegrityError",
            fields=[
                (
                    "modelwithuniqueslug_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="autoslug.modelwithuniqueslug",
                    ),
                ),
            ],
            bases=("autoslug.modelwithuniqueslug",),
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugFKNull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique_with=("simple_model",),
                    ),
                ),
                (
                    "simple_model",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoslug.simplemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithUniqueSlugFK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    vendor.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique_with=("simple_model__name",),
                    ),
                ),
                (
                    "simple_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoslug.simplemodel",
                    ),
                ),
            ],
        ),
    ]
